language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t xmxlza/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true xmxlza/react-test npm run test

after_success:
  - docker build -t xmxlza/multi-client ./client
  - docker build -t xmxlza/multi-nginx ./nginx
  - docker build -t xmxlza/multi-server ./server
  - docker build -t xmxlza/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push xmxlza/multi-client
  - docker push xmxlza/multi-nginx
  - docker push xmxlza/multi-server
  - docker push xmxlza/multi-worker





